# Keystone (Identity Service)
- name: Install Keystone packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - openstack-keystone
    - httpd
    - mod_wsgi

- name: Configure MySQL database for Keystone
  mysql_db:
    name: keystone
    state: present

- name: Grant privileges on Keystone database
  mysql_user:
    name: keystone
    host: "{{ item }}"
    password: "KEYSTONE_DBPASS"
    priv: "keystone.*:ALL"
    state: present
  loop:
    - 'localhost'
    - '%'

- name: Configure Keystone
  block:
    - name: Configure Keystone database connection
      ini_file:
        path: /etc/keystone/keystone.conf
        section: database
        option: connection
        value: "mysql+pymysql://keystone:KEYSTONE_DBPASS@controller/keystone"
      notify: Restart Apache

    - name: Configure Fernet token provider
      ini_file:
        path: /etc/keystone/keystone.conf
        section: token
        option: provider
        value: fernet
      notify: Restart Apache

    - name: Populate Keystone database
      command: su -s /bin/sh -c "keystone-manage db_sync" keystone
      notify: Restart Apache

    - name: Initialize Fernet key repositories
      command: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
      notify: Restart Apache

    - name: Bootstrap Keystone service
      command: keystone-manage bootstrap --bootstrap-password ADMIN_PASS --bootstrap-admin-url http://controller:5000/v3/ --bootstrap-internal-url http://controller:5000/v3/ --bootstrap-public-url http://controller:5000/v3/ --bootstrap-region-id RegionOne
      notify: Restart Apache
  tags:
    - keystone_configuration

- name: Configure Apache
  block:
    - name: Configure Apache ServerName
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        line: "ServerName controller"
      notify: Restart Apache

    - name: Restart Apache
      service:
        name: httpd
        state: restarted
  tags:
    - apache_configuration

- name: Configure Keystone environment variables
  block:
    - name: Set Keystone environmental variables
      lineinfile:
        path: /etc/environment
        line: "{{ item }}"
      with_items:
        - 'export OS_USERNAME=admin'
        - 'export OS_PASSWORD=ADMIN_PASS'
        - 'export OS_PROJECT_NAME=admin'
        - 'export OS_USER_DOMAIN_NAME=Default'
        - 'export OS_PROJECT_DOMAIN_NAME=Default'
        - 'export OS_AUTH_URL=http://controller:5000/v3'
        - 'export OS_IDENTITY_API_VERSION=3'
  tags:
    - environment_configuration

handlers:
  - name: Restart Apache
    service:
      name: httpd
      state: restarted


# Glance (Imaging Service)
- name: install glance
  yum:
    name: openstack-glance
    state: present

- name: restart glance
  service:
      name: openstack-glance-api
      state: started

# Nova (Compute Service)
- name: install nova
  yum:
    name:
      - openstack-nova-api
      - openstack-nova-conductor
      - openstack-nova-novncproxy
      - openstack-nova-scheduler
    state: present

- name: restart nova-api service
  service:
    name: openstack-nova-api
    state: started

- name: restart nova-scheduler service
  service:
    name: openstack-nova-scheduler
    state: started

- name: restart nova-conductor service
  service:
    name: openstack-nova-conductor
    state: started

- name: restart nova-novncproxy service
  service:
    name: openstack-nova-novncproxy
    state: started
