# Keystone (Identity Service)
- name: install keystone
  apt:
    name: keystone
    state: present

- name: restart apache2
  service:
    name: apache2
    state: restarted

# Glance (Imaging Service)
- name: install glance
  apt:
    name: glance
    state: present

- name: restart glance
  service:
    name: glance-api
    state: restarted

# Nova (Compute Service)
- name: install nova
  apt:
    name:
      - nova-api
      - nova-conductor
      - nova-novncproxy
      - nova-scheduler
    state: present

- name: restart nova-api service
  service:
    name: nova-api
    state: restarted

- name: restart nova-scheduler service
  service:
    name: nova-scheduler
    state: restarted

- name: restart nova-conductor service
  service:
    name: nova-conductor
    state: restarted

- name: restart nova-novncproxy service
  service:
    name: nova-novncproxy
    state: restarted
